export const routePaths = {
  Main: "/",
  Art: "/art",
  Auth: "/auth",
  Nickname: "/nickname",
  Profile: "/profile",
  Category: "/category",
  Create: "/create",
  Post: "/post",
  PostId: "/:postId",
  Post_Detail: "/detail",
  Post_Upload: "/upload",
  Post_Edit: "/edit",
  Post_Delete: "/delete",
  MyPage: "/my-page",
};
